### ISSUE TITLE
db error when running `nikola build` from master

### ISSUE THREAD

**Issue by johanv** [draga79/nikola#1]
Hi,
Thank you for creating this image.
I found a bug (I think) in the master image. If I run
```
docker run --rm -ti -v $PWD:/nikola dragas/nikola nikola build
```
I get this error:
```
Scanning posts........done!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/doit/dependency.py", line 139, in __init__
    self._dbm = ddbm.open(self.name, 'c')
  File "/usr/lib/python3.5/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/usr/local/lib/python3.5/dist-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/usr/local/lib/python3.5/dist-packages/doit/cmd_base.py", line 406, in execute
    db_class, params['dep_file'], checker_cls)
  File "/usr/local/lib/python3.5/dist-packages/doit/dependency.py", line 475, in __init__
    self.backend = db_class(backend_name)
  File "/usr/local/lib/python3.5/dist-packages/doit/dependency.py", line 154, in __init__
    raise DatabaseException(message)
doit.dependency.DatabaseException: db type is dbm.gnu, but the module is not available
```
When I use the alpine image, like this:
```
docker run --rm -ti -v $PWD:/nikola dragas/nikola:alpine nikola build
```
It works like a charm.

I just wanted to let you know.

**Comment by draga79** [comment]
Thank you for your feedback!
I'll be looking at it ASAP. I also think I'll promote the alpine branch as "master" as it's smaller and efficient.

**Comment by draga79** [comment]
Hi,
I've tried to init and build a newly-created nikola website with Debian image but I had no issues. Maybe you were trying to build an externally created nikola site? Anyway, I've merged alpine branch to Master, so now master is actually Alpine.
